### ISSUE TITLE
additional setup issues

### ISSUE THREAD

**Issue by roycewilliams** [JarrettR/FPGA-Cryptoparty#2]
FPGA/host/run.sh shows:

`java -cp wpa2.jar Wpa2`

... but this currently fails with:

Error: Could not find or load main class Wpa2

This looks closer:

`sudo java -cp wpa2.jar WPA2`

... but this also fails (at least on my setup), with:

Firmware upload time: 101 ms
4 FPGA's found
FPGA 0: FPGA configuration time: 79 ms
Warning (try 1): error sending control message: Connection timed out
Error: bus=001  device=027: selectFPGA: error sending control message: Connection timed out

dmesg shows:

[ 5658.360040] usb 1-2.4.3: new high-speed USB device number 27 using ehci-pci
[ 5658.468923] usb 1-2.4.3: New USB device found, idVendor=221a, idProduct=0100
[ 5658.468934] usb 1-2.4.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 5658.468938] usb 1-2.4.3: Product: WPA2 for UFM 1.15y
[ 5658.468946] usb 1-2.4.3: Manufacturer: ZTEX
[ 5658.468949] usb 1-2.4.3: SerialNumber: [redacted]
[ 5659.984303] usb 1-2.4.3: usbfs: USBDEVFS_CONTROL failed cmd java rqt 64 rq 81 len 0 ret -110

[Edit - note that this is a known-working board - works with JtR jumbo]

**Comment by JarrettR** [comment]
You're right about the main class being uppercase.
For the other stuff, you'd likely have to recompile and force firmware upload:
```
make
sudo java -cp wpa2.jar WPA2 -f
```

The result won't be particularly useful right now - I'm still writing a proper protocol for the host communication, my available time has been pretty limited lately. Hopefully done in the next week or two!

**Comment by roycewilliams** [comment]
Fair enough! FWIW, these may be useful as reference. They work well in my testing.

https://github.com/Apingis/ztex_inouttraffic
https://github.com/magnumripper/JohnTheRipper/tree/bleeding-jumbo/src/ztex
